/**
 * feature-catalog.ts — GENERATED by scripts/sync-feature-catalog.mjs. DO NOT
 * EDIT BY HAND. Re-run `npm run sync:features` when the engine catalogs change.
 *
 * The UNIFIED list of every editor feature an admin can compose into a package,
 * derived from the engine's two sources (core/plugin catalog + premium
 * registry). ONE license grants a set of these ids; the editor gates BOTH its
 * core features and its premium plugins from that same set. `sellable=false` =
 * never offered (internal/test or deprecated).
 */

export type FeatureKind = 'core' | 'plugin' | 'premium';

export interface CatalogFeature {
  id: string;
  title: string;
  group: string;
  kind: FeatureKind;
  deprecated?: boolean;
  sellable: boolean;
}

export const FEATURE_CATALOG: CatalogFeature[] = [
  { id: 'text.bold', title: 'Bold', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.italic', title: 'Italic', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.underline', title: 'Underline', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.strikethrough', title: 'Strikethrough', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.superscript', title: 'Superscript', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.subscript', title: 'Subscript', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.inlineCode', title: 'Inline code', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.decoration', title: 'Overline / dotted underline', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.changeCase', title: 'Change case', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'text.transform', title: 'Text-transform (CSS)', group: 'Text formatting', kind: 'core', sellable: true },
  { id: 'font.family', title: 'Font family', group: 'Font', kind: 'core', sellable: true },
  { id: 'font.size', title: 'Font size', group: 'Font', kind: 'core', sellable: true },
  { id: 'font.lineHeight', title: 'Line height', group: 'Font', kind: 'core', sellable: true },
  { id: 'font.weight', title: 'Font weight', group: 'Font', kind: 'core', sellable: true },
  { id: 'font.spacing', title: 'Letter spacing / indent', group: 'Font', kind: 'core', sellable: true },
  { id: 'color.text', title: 'Text color', group: 'Color', kind: 'core', sellable: true },
  { id: 'color.background', title: 'Background (highlight) color', group: 'Color', kind: 'core', sellable: true },
  { id: 'paragraph.headings', title: 'Headings (H1–H6)', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'paragraph.blockquote', title: 'Block quote', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'paragraph.codeBlock', title: 'Code block', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'paragraph.alignment', title: 'Alignment', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'paragraph.styles', title: 'Named styles', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'paragraph.language', title: 'Text-part language', group: 'Paragraph', kind: 'core', sellable: true },
  { id: 'list.bullet', title: 'Bullet list', group: 'Lists', kind: 'core', sellable: true },
  { id: 'list.ordered', title: 'Numbered list', group: 'Lists', kind: 'core', sellable: true },
  { id: 'list.indent', title: 'Indent / outdent', group: 'Lists', kind: 'core', sellable: true },
  { id: 'list.style', title: 'List style + start', group: 'Lists', kind: 'core', sellable: true },
  { id: 'insert.hr', title: 'Horizontal rule', group: 'Insert', kind: 'core', sellable: true },
  { id: 'insert.pageBreak', title: 'Page break', group: 'Insert', kind: 'core', sellable: true },
  { id: 'insert.html', title: 'Insert raw HTML/text', group: 'Insert', kind: 'core', sellable: true },
  { id: 'tools.showBlocks', title: 'Show block outlines', group: 'Tools', kind: 'core', sellable: true },
  { id: 'tools.fullscreen', title: 'Fullscreen', group: 'Tools', kind: 'core', sellable: true },
  { id: 'tools.print', title: 'Print', group: 'Tools', kind: 'core', sellable: true },
  { id: 'insert.link', title: 'Links', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.image', title: 'Images', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.table', title: 'Tables', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.media', title: 'Video / media embeds', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.emoji', title: 'Emoji', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.specialChars', title: 'Special characters', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.bookmark', title: 'Bookmarks', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'insert.mentions', title: '@Mentions', group: 'Insert', kind: 'plugin', sellable: true },
  { id: 'tools.findReplace', title: 'Find & replace', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.source', title: 'Source view', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.preview', title: 'Preview', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.spellcheck', title: 'Spellcheck', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.speech', title: 'Dictation (speech to text)', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.formatPainter', title: 'Format painter', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.codeBlock', title: 'Code block (plugin)', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.slashCommand', title: 'Slash commands', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.autoformat', title: 'Markdown autoformat', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.blockDrag', title: 'Block drag-reorder', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'tools.resizeEditor', title: 'Resizable editor', group: 'Tools', kind: 'plugin', sellable: true },
  { id: 'edit.todoList', title: 'To-do lists', group: 'Lists', kind: 'plugin', sellable: true },
  { id: 'export.pdf', title: 'Export to PDF', group: 'Export & Import', kind: 'premium', sellable: true },
  { id: 'export.docx', title: 'Export to Word (DOCX)', group: 'Export & Import', kind: 'premium', sellable: true },
  { id: 'export.markdown', title: 'Markdown Export', group: 'Export & Import', kind: 'premium', sellable: false },
  { id: 'import.word', title: 'Word Import (DOCX → editor)', group: 'Export & Import', kind: 'premium', sellable: false },
  // SEO is DEPRECATED + NON-SELLABLE (product decision: not shipping SEO, same as
  // AI). Plugin code retained in premium/seo (additive-only) so an existing
  // license still verifies via honorSnapshot, but `isSellableFeature` returns
  // false → an admin can never add it to a new package. Re-enable = deprecated:false + sellable:true.
  { id: 'seo', title: 'SEO Analyzer', group: 'Premium', kind: 'premium', deprecated: true, sellable: false },
  { id: 'footnotes', title: 'Footnotes', group: 'Premium', kind: 'premium', deprecated: true, sellable: false },
  { id: 'versionHistory', title: 'Version History', group: 'Collaboration', kind: 'premium', sellable: false },
  { id: 'comments', title: 'Comments', group: 'Collaboration', kind: 'premium', sellable: false },
  { id: 'track.changes', title: 'Track Changes / Suggestion Mode', group: 'Collaboration', kind: 'premium', sellable: false },
  { id: 'collab.rt', title: 'Real-time Collaboration', group: 'Collaboration', kind: 'premium', sellable: false },
  // AI features are DEPRECATED + NON-SELLABLE (product decision: this product
  // does not ship AI). Kept in the catalog as KNOWN ids (not deleted) so any
  // pre-existing license carrying them still verifies/renews via honorSnapshot —
  // but `isSellableFeature` returns false, so an admin can NEVER add them to a
  // new package, and they never appear in the sellable list. Same treatment as
  // `footnotes`. To re-enable AI later, set deprecated:false + sellable:true.
  { id: 'ai.panel', title: 'AI Writing Panel (Chat)', group: 'AI', kind: 'premium', deprecated: true, sellable: false },
  { id: 'ai.quickActions', title: 'AI Quick Actions (rewrite/summarize/tone)', group: 'AI', kind: 'premium', deprecated: true, sellable: false },
  { id: 'ai.review', title: 'AI Review (suggestions)', group: 'AI', kind: 'premium', deprecated: true, sellable: false },
  { id: 'ai.translate', title: 'AI Translate', group: 'AI', kind: 'premium', deprecated: true, sellable: false },
  { id: 'restrictedEditing.roles', title: 'Restricted Editing — role-based zones', group: 'Premium', kind: 'premium', sellable: false },
  { id: 'lists.legal', title: 'Multi-level Legal Lists', group: 'Premium', kind: 'premium', sellable: false },
  { id: 'outline.toc', title: 'Document Outline + Table of Contents', group: 'Premium', kind: 'premium', sellable: false },
  { id: 'mergeFields', title: 'Merge Fields + Content Templates', group: 'Premium', kind: 'premium', sellable: false },
  { id: 'pagination', title: 'Pagination', group: 'Premium', kind: 'premium', sellable: false },
  { id: 'dev.smoke', title: 'Internal smoke-test feature (never sold)', group: 'Premium', kind: 'premium', sellable: false },
];

const BY_ID = new Map(FEATURE_CATALOG.map((f) => [f.id, f]));

/** Is this a known engine feature id? */
export function isKnownFeature(id: string): boolean {
  return BY_ID.has(id);
}

/** Is this feature allowed to be composed into a sellable package? */
export function isSellableFeature(id: string): boolean {
  const f = BY_ID.get(id);
  return !!f && f.sellable && !f.deprecated;
}
