/**
 * session.dto.ts — request shape for POST /delivery/session (§1.3).
 *
 * Every field is optional: an anonymous free caller sends an effectively empty
 * body and still receives a working editor. That frictionless free path is what
 * drives adoption, so it must not require a key, an account, or a signup.
 */
import { IsOptional, IsString, MaxLength } from 'class-validator';

/**
 * Refresh a near-expiry session token (D1).
 *
 * The refresh token is the only credential: the licence key never has to be
 * re-sent, and entitlements are re-resolved from the licence server-side, so a
 * refresh can never mint access that was not already granted.
 */
export class RefreshSessionDto {
  @IsString()
  @MaxLength(4096)
  token!: string;

  /**
   * The long-lived refresh token, tried when `token` has expired (E3).
   *
   * The engine refreshes with whatever is in `licenseKey` — the 15-minute
   * SESSION token — so a tab reopened after a lunch break presents one that is
   * past `exp` and fails verification. Without this the caller would silently
   * drop to the free tier despite holding a valid 30-day credential.
   */
  @IsOptional()
  @IsString()
  @MaxLength(4096)
  refreshToken?: string;
}

export class SessionRequestDto {
  /** Licence key (Path A). Absent for free/anonymous callers. */
  @IsOptional()
  @IsString()
  @MaxLength(4096)
  licenceKey?: string;

  /**
   * Anonymous install identifier (Path B, T18). Generated by the loader on
   * first run and sent on every session, so anonymous traffic can be rate
   * limited per install and usage attributed (S1) rather than being an
   * undifferentiated flood of per-IP requests.
   */
  @IsOptional()
  @IsString()
  @MaxLength(128)
  installId?: string;

  /**
   * A specific engine version to load. Honoured only when the licence has no
   * pin of its own — a customer must not be able to escape an admin's
   * deliberate pinning by asking for a different build.
   */
  @IsOptional()
  @IsString()
  @MaxLength(32)
  version?: string;
}
